replicaCount: 1

nginx:
  image:
    repository: mirror.gcr.io/nginx
    pullPolicy: IfNotPresent
    tag: ""
    volumeMounts: []
    resources: {}

cloudSdk:
  image: 
    repository: mirror.gcr.io/google/cloud-sdk
    pullPolicy: IfNotPresent
    tag: ""
    volumeMounts: []
    resources: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
nodeSelector: {}
tolerations: []
affinity: {}
