apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-gcp-private-mirror.fullname" . }}-nginx-config
data:
  nginx.conf: |-
    {{- .Files.Get "resources/nginx.conf.template" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-gcp-private-mirror.fullname" . }}-nginx-env
data:
  NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
  TOKEN_FILE_PATH: {{ .Values.nginx.tokenFilePath | quote }}
  PROXY_BUFFER_SIZE: {{ .Values.nginx.proxy.bufferSize | quote }}
  PROXY_BUFFERS: {{ .Values.nginx.proxy.buffers | quote }}
  PROXY_BUSY_BUFFERS_SIZE: {{ .Values.nginx.proxy.busyBuffersSize | quote }}
  LARGE_CLIENT_HEADER_BUFFERS: {{ .Values.nginx.proxy.largeClientHeaderBuffers | quote }}
  UPSTREAM_HOST: {{ .Values.nginx.proxy.upstreamHost | quote }}
  UPSTREAM_PROTOCOL: {{ .Values.nginx.proxy.upstreamProtocol | quote }}
  BASE_REWRITE_PATH: {{ .Values.nginx.proxy.rewritePath | quote }}
  TOKEN_CACHE_EXPIRATION_SECONDS: {{ .Values.nginx.proxy.tokenCacheExpirationSeconds | quote }}
  MAX_AUTH_RETRY_ATTEMPTS: {{ .Values.nginx.proxy.maxAuthRetryAttempts | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-gcp-private-mirror.fullname" . }}-cloud-sdk-script
data:
  generate-token-file.sh: |-
    {{- .Values.cloudSdk.script | default (.Files.Get "resources/generate-token-file.sh") | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-gcp-private-mirror.fullname" . }}-cloud-sdk-env
data:
  TOKEN_FILE_PATH: {{ .Values.nginx.tokenFilePath | quote }}