replicaCount: 1

nameOverride: ""
fullnameOverride: ""

bufferSize: "256k"
buffers: "8 256k"
busyBuffersSize: "512k"
largeClientHeaderBuffers: "32 5120k"
upstreamHost: "europe-docker.pkg.dev"
upstreamProtocol: "https"
rewritePath: "gcp_project/registry_name"
tokenCacheExpirationSeconds: "300"
maxAuthRetryAttempts: "1"
authTokenEndpoint: ""
dnsResolver: "kube-dns.kube-system.svc.cluster.local"

image:
  repository: sguesdon/gke-nginx-mirror-gke
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []
volumeMounts: []
resources: {}
probes:
  readinessProbe:
    httpGet:
      path: /health
      port: http
  livenessProbe:
    httpGet:
      path: /health
      port: http

serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}
  # annotations:
  #   iam.gke.io/gcp-service-account: my-gcp-sa@my-sa-project-id.iam.gserviceaccount.com

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
nodeSelector: {}
tolerations: []
affinity: {}
