replicaCount: 1

nginx:
  image:
    repository: fabiocicerchia/nginx-lua
    pullPolicy: IfNotPresent
    tag: ""
  volumeMounts: []
  resources: {}
  securityContext: {}
  tokenFilePath: /config/token
  proxy:
    bufferSize: '128k'
    buffers: '4 256k'
    busyBuffersSize: '256k'
    largeClientHeaderBuffers: '16 5120k'
    upstreamHost: 'europe-docker.pkg.dev'
    upstreamProtocol: 'https'
    rewritePath: 'gcp_project/registry_name'
    tokenCacheExpirationSeconds: '300'
    maxAuthRetryAttempts: '1'

cloudSdk:
  image:
    repository: mirror.gcr.io/google/cloud-sdk
    pullPolicy: IfNotPresent
    tag: ""
  volumeMounts: []
  resources: {}
  securityContext: {}
  script: null

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
nodeSelector: {}
tolerations: []
affinity: {}
