name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish helm chart
        run: |
          helm registry login registry-1.docker.io -u ${{ secrets.DOCKER_USERNAME }}
          devbox script publish oci://registry-1.docker.io/docker-gcp-private-mirror ${{ github.ref_name }}
     
  update_docker_description:
    name: Update docker hub description
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update docker hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
