name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Check tests passed
        uses: actions/github-script@v7
        with:
          script: |
            const { data: workflows } = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              status: 'success',
            });
            const recentRun = workflows.workflow_runs.find(run => run.head_commit.id === process.env.GITHUB_SHA);
            if (!recentRun) {
              core.setFailed('Tests did not pass successfully for this commit.');
            }

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish helm chart
        run: |
          helm registry login registry-1.docker.io -u ${{ secrets.DOCKER_USERNAME }}
          devbox script publish oci://registry-1.docker.io/docker-gcp-private-mirror ${{ github.ref_name }}