name: Deploy
on:
  push:
    tags:
      - "*"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install devbox
        uses: jetify-com/devbox-install-action@a03caf5813591bc882139eba6ae947930a83a427 # v0.11.0

      - name: Publish helm chart
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | helm registry login registry-1.docker.io -u ${DOCKER_USERNAME} --password-stdin
          devbox run publish oci://registry-1.docker.io/sguesdon ${{ github.ref_name }}
