name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Publish helm chart
        run: |
          helm registry login registry-1.docker.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          devbox script publish oci://registry-1.docker.io/docker-gcp-private-mirror ${{ github.ref_name }}
