name: Tests
on:
  pull_request:
    branches:
      - main
jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
      
      - name: Start minikube
        uses: medyagh/setup-minikube@latest

      - name: Deploy helm chart
        run: |
          helm package . --version=0.0.1
          helm install private-gcp-mirror ./docker-gcp-private-mirror-0.0.1.tgz

      - name: Run tests
        run: |
          devbox run test
