name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install devbox
        uses: jetify-com/devbox-install-action@41a0b3f5c44de6f46b1e79c8bb19d2a74a3b4f83 # v0.12.0

      - name: Start minikube
        uses: medyagh/setup-minikube@317d92317e473a10540357f1f4b2878b80ee7b95 # v0.0.18

      - name: Run tests
        env:
          MINIKUBE: true
        run: |
          devbox run test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install devbox
        uses: jetify-com/devbox-install-action@41a0b3f5c44de6f46b1e79c8bb19d2a74a3b4f83 # v0.12.0

      - name: Run helm lint
        run: |
          devbox run lint
